"""fix menmber to member_since

Revision ID: dc27b2ac02d5
Revises: 1d0d5da1b8df
Create Date: 2018-04-29 22:21:04.954535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc27b2ac02d5'
down_revision = '1d0d5da1b8df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('member_since', sa.DateTime(), nullable=True))
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_column('menmber_since')
    # op.drop_column('users', 'menmber_since')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('menmber_since', sa.DATETIME(), nullable=True))
    op.drop_column('users', 'member_since')
    # ### end Alembic commands ###
